### ISSUE TITLE
Alignment of label for figures doesn't respect the alignment

### ISSUE THREAD

**Issue by otavio** [asciidoctor/asciidoctor-fopub#44]
When a figure is aligned to 'center' the title is not.

I found a code which supposedly does this:

https://gist.github.com/otavio/e3ec21d9667c5c4fa0d0

However FOP is not happy with it, triggering:

<pre>
org.apache.xpath.XPathException: Can not convert #STRING to a NodeList!
        at org.apache.xpath.objects.XObject.error(XObject.java:702)
        at org.apache.xpath.objects.XObject.iter(XObject.java:405)
        at org.apache.xpath.Expression.asIterator(Expression.java:250)
...
</pre>

So I think something in the line of the above code could  do the trick but the xpath seems wrong.

**Comment by mojavelinux** [comment]
I commented on the gist. I think you are right that the xpath query was mistyped.
