### ISSUE TITLE
Math: JEuclid error

### ISSUE THREAD

**Issue by asprionj** [asciidoctor/asciidoctor-fopub#99]
I run into the same problem described in [this thread on discuss.asciidoctor.org](https://discuss.asciidoctor.org/Error-running-asciidoctor-fopub-td6928.html). I just want to generate a PDF out of a "playground" ADOC file with everything in it that's of interest for me. Until I added math, everything was working fine. Below is the full output I get.

I just cloned the `asciidoctor-fopub` repo yesterday and followed the instructions. So it uses fop 2.1. Any hints on what's going wrong? Being able to also render math to PDF would be the killer-feature for me to use asciidoctor for virtually everything :wink:

```
Sep 22, 2019 8:29:27 PM org.apache.fop.events.LoggingEventListener processEvent
WARNING: Font "Symbol,normal,700" not found. Substituting with "Symbol,normal,400".
Sep 22, 2019 8:29:27 PM org.apache.fop.events.LoggingEventListener processEvent
WARNING: Font "ZapfDingbats,normal,700" not found. Substituting with "ZapfDingbats,normal,400".
Sep 22, 2019 8:29:28 PM org.apache.fop.events.LoggingEventListener processEvent
WARNING: Glyph "◦" (0x25e6, openbullet) not available in font "Helvetica".
Sep 22, 2019 8:29:28 PM org.apache.fop.events.LoggingEventListener processEvent
INFO: Rendered page #1.
Exception in thread "main" java.lang.NoClassDefFoundError: org/w3c/dom/events/CustomEvent
	at java.base/java.lang.Class.getDeclaredFields0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredFields(Class.java:3061)
	at java.base/java.lang.Class.getField0(Class.java:3246)
	at java.base/java.lang.Class.getField(Class.java:1997)
	at net.sourceforge.jeuclid.elements.JEuclidElementFactory.addClass(JEuclidElementFactory.java:146)
	at net.sourceforge.jeuclid.elements.JEuclidElementFactory.<clinit>(JEuclidElementFactory.java:186)
	at net.sourceforge.jeuclid.elements.generic.DocumentElement.createElementNS(DocumentElement.java:165)
	at org.apache.xml.utils.DOMBuilder.startElement(DOMBuilder.java:324)
	at org.apache.xml.serializer.ToXMLSAXHandler.closeStartTag(ToXMLSAXHandler.java:204)
	at org.apache.xml.serializer.ToSAXHandler.flushPending(ToSAXHandler.java:277)
	at org.apache.xml.serializer.ToXMLSAXHandler.startPrefixMapping(ToXMLSAXHandler.java:348)
	at org.apache.xalan.templates.ElemElement.constructNode(ElemElement.java:328)
	at org.apache.xalan.templates.ElemElement.execute(ElemElement.java:288)
	at org.apache.xalan.transformer.TransformerImpl.executeChildTemplates(TransformerImpl.java:2411)
	at org.apache.xalan.templates.ElemChoose.execute(ElemChoose.java:139)
	at org.apache.xalan.templates.ElemApplyTemplates.transformSelectedNodes(ElemApplyTemplates.java:393)
	at org.apache.xalan.templates.ElemApplyTemplates.execute(ElemApplyTemplates.java:176)
	at org.apache.xalan.transformer.TransformerImpl.executeChildTemplates(TransformerImpl.java:2411)
	at org.apache.xalan.templates.ElemElement.constructNode(ElemElement.java:339)
	at org.apache.xalan.templates.ElemElement.execute(ElemElement.java:288)
	at org.apache.xalan.transformer.TransformerImpl.executeChildTemplates(TransformerImpl.java:2411)
	at org.apache.xalan.templates.ElemChoose.execute(ElemChoose.java:139)
	at org.apache.xalan.transformer.TransformerImpl.executeChildTemplates(TransformerImpl.java:2411)
	at org.apache.xalan.transformer.TransformerImpl.applyTemplateToNode(TransformerImpl.java:2281)
	at org.apache.xalan.transformer.TransformerImpl.transformNode(TransformerImpl.java:1367)
	at org.apache.xalan.transformer.TransformerImpl.transform(TransformerImpl.java:709)
	at org.apache.xalan.transformer.TransformerImpl.transform(TransformerImpl.java:1284)
	at org.apache.xalan.transformer.TransformerImpl.transform(TransformerImpl.java:1262)
	at net.sourceforge.jeuclid.DOMBuilder.applyTransform(DOMBuilder.java:217)
	at net.sourceforge.jeuclid.DOMBuilder.createJeuclidDom(DOMBuilder.java:196)
	at net.sourceforge.jeuclid.layout.JEuclidView.<init>(JEuclidView.java:75)
	at net.sourceforge.jeuclid.fop.JEuclidElement.calculate(JEuclidElement.java:110)
	at net.sourceforge.jeuclid.fop.JEuclidElement.getDimension(JEuclidElement.java:122)
	at org.apache.fop.fo.flow.InstreamForeignObject.prepareIntrinsicSize(InstreamForeignObject.java:112)
	at org.apache.fop.fo.flow.InstreamForeignObject.getIntrinsicWidth(InstreamForeignObject.java:125)
	at org.apache.fop.layoutmgr.inline.AbstractGraphicsLayoutManager.getInlineArea(AbstractGraphicsLayoutManager.java:60)
	at org.apache.fop.layoutmgr.inline.AbstractGraphicsLayoutManager.getNextKnuthElements(AbstractGraphicsLayoutManager.java:116)
	at org.apache.fop.layoutmgr.inline.LineLayoutManager.collectInlineKnuthElements(LineLayoutManager.java:700)
	at org.apache.fop.layoutmgr.inline.LineLayoutManager.getNextKnuthElements(LineLayoutManager.java:629)
	at org.apache.fop.layoutmgr.BlockLayoutManager.getNextChildElements(BlockLayoutManager.java:141)
	at org.apache.fop.layoutmgr.BlockStackingLayoutManager.getNextKnuthElements(BlockStackingLayoutManager.java:289)
	at org.apache.fop.layoutmgr.BlockLayoutManager.getNextKnuthElements(BlockLayoutManager.java:113)
	at org.apache.fop.layoutmgr.BlockLayoutManager.getNextKnuthElements(BlockLayoutManager.java:105)
	at org.apache.fop.layoutmgr.BlockLayoutManager.getNextChildElements(BlockLayoutManager.java:141)
	at org.apache.fop.layoutmgr.BlockStackingLayoutManager.getNextKnuthElements(BlockStackingLayoutManager.java:289)
	at org.apache.fop.layoutmgr.BlockLayoutManager.getNextKnuthElements(BlockLayoutManager.java:113)
	at org.apache.fop.layoutmgr.BlockLayoutManager.getNextKnuthElements(BlockLayoutManager.java:105)
	at org.apache.fop.layoutmgr.BlockLayoutManager.getNextChildElements(BlockLayoutManager.java:141)
	at org.apache.fop.layoutmgr.BlockStackingLayoutManager.getNextKnuthElements(BlockStackingLayoutManager.java:289)
	at org.apache.fop.layoutmgr.BlockLayoutManager.getNextKnuthElements(BlockLayoutManager.java:113)
	at org.apache.fop.layoutmgr.BlockLayoutManager.getNextKnuthElements(BlockLayoutManager.java:105)
	at org.apache.fop.layoutmgr.FlowLayoutManager.getNextChildElements(FlowLayoutManager.java:223)
	at org.apache.fop.layoutmgr.FlowLayoutManager.addChildElements(FlowLayoutManager.java:147)
	at org.apache.fop.layoutmgr.FlowLayoutManager.getNextKnuthElements(FlowLayoutManager.java:116)
	at org.apache.fop.layoutmgr.FlowLayoutManager.getNextKnuthElements(FlowLayoutManager.java:69)
	at org.apache.fop.layoutmgr.PageBreaker.getNextKnuthElements(PageBreaker.java:254)
	at org.apache.fop.layoutmgr.AbstractBreaker.getNextBlockList(AbstractBreaker.java:752)
	at org.apache.fop.layoutmgr.PageBreaker.getNextBlockList(PageBreaker.java:180)
	at org.apache.fop.layoutmgr.PageBreaker.getNextBlockList(PageBreaker.java:160)
	at org.apache.fop.layoutmgr.AbstractBreaker.doLayout(AbstractBreaker.java:388)
	at org.apache.fop.layoutmgr.PageBreaker.doLayout(PageBreaker.java:114)
	at org.apache.fop.layoutmgr.PageSequenceLayoutManager.activateLayout(PageSequenceLayoutManager.java:138)
	at org.apache.fop.area.AreaTreeHandler.endPageSequence(AreaTreeHandler.java:267)
	at org.apache.fop.fo.pagination.PageSequence.endOfNode(PageSequence.java:130)
	at org.apache.fop.fo.FOTreeBuilder$MainFOHandler.endElement(FOTreeBuilder.java:360)
	at org.apache.fop.fo.FOTreeBuilder.endElement(FOTreeBuilder.java:190)
	at org.apache.xml.serializer.ToXMLSAXHandler.endElement(ToXMLSAXHandler.java:261)
	at org.apache.xalan.templates.ElemLiteralResult.execute(ElemLiteralResult.java:1399)
	at org.apache.xalan.templates.ElemApplyTemplates.transformSelectedNodes(ElemApplyTemplates.java:393)
	at org.apache.xalan.templates.ElemApplyTemplates.execute(ElemApplyTemplates.java:176)
	at org.apache.xalan.transformer.TransformerImpl.executeChildTemplates(TransformerImpl.java:2411)
	at org.apache.xalan.templates.ElemLiteralResult.execute(ElemLiteralResult.java:1374)
	at org.apache.xalan.templates.ElemApplyTemplates.transformSelectedNodes(ElemApplyTemplates.java:393)
	at org.apache.xalan.templates.ElemApplyTemplates.execute(ElemApplyTemplates.java:176)
	at org.apache.xalan.templates.ElemApplyTemplates.transformSelectedNodes(ElemApplyTemplates.java:393)
	at org.apache.xalan.templates.ElemApplyTemplates.execute(ElemApplyTemplates.java:176)
	at org.apache.xalan.transformer.TransformerImpl.executeChildTemplates(TransformerImpl.java:2411)
	at org.apache.xalan.templates.ElemIf.execute(ElemIf.java:160)
	at org.apache.xalan.transformer.TransformerImpl.executeChildTemplates(TransformerImpl.java:2411)
	at org.apache.xalan.templates.ElemChoose.execute(ElemChoose.java:139)
	at org.apache.xalan.transformer.TransformerImpl.executeChildTemplates(TransformerImpl.java:2411)
	at org.apache.xalan.templates.ElemChoose.execute(ElemChoose.java:139)
	at org.apache.xalan.transformer.TransformerImpl.executeChildTemplates(TransformerImpl.java:2411)
	at org.apache.xalan.templates.ElemChoose.execute(ElemChoose.java:139)
	at org.apache.xalan.transformer.TransformerImpl.executeChildTemplates(TransformerImpl.java:2411)
	at org.apache.xalan.transformer.TransformerImpl.applyTemplateToNode(TransformerImpl.java:2281)
	at org.apache.xalan.transformer.TransformerImpl.transformNode(TransformerImpl.java:1367)
	at org.apache.xalan.transformer.TransformerImpl.transform(TransformerImpl.java:709)
	at org.apache.xalan.transformer.TransformerImpl.transform(TransformerImpl.java:1284)
	at org.apache.xalan.transformer.TransformerImpl.transform(TransformerImpl.java:1262)
	at org.apache.fop.cli.InputHandler.transformTo(InputHandler.java:297)
	at org.apache.fop.cli.InputHandler.renderTo(InputHandler.java:126)
	at org.apache.fop.cli.Main.startFOP(Main.java:186)
	at org.apache.fop.cli.Main.main(Main.java:217)
Caused by: java.lang.ClassNotFoundException: org.w3c.dom.events.CustomEvent
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 94 more
```

**Comment by fdeitylink** [comment]
I had this issue too and managed to "fix" it by downgrading to Java 8. Java 9 might work too.
I got the hint to do this from [here](http://apache-fop.1065347.n5.nabble.com/FOP-2-3-and-JEuclid-tp46682p46683.html).

Not ideal but seems to work for now.
